### PR TITLE
upgrade to 0.19 version

### LINKED ISSUE #1: Upgrade to Elm 0.19

### PR DESCRIPTION
**Pull request by Kr00lIX**
Fixes #1

### CODE REVIEW

**Review by r-k-b — APPROVED** [review]
lgtm 👍

**Comment by Kr00lIX** [comment]
@r-k-b I would appreciate it if you publish a new version of a package with these changes

**Comment by r-k-b** [comment]
@Kr00lIX ah of course! ~I've just run `elm package publish`, but it might take some time to appear on [package.elm-lang.org](https://package.elm-lang.org/packages/r-k-b/elm-interval/latest/Interval) (if I've done it correctly? Been a while...)~

Yep I forgot to pull the changes 🤦‍♂. I'll have to remove the `Debug` call before publishing; this might be a good time to change the signature to replace those `List interval` arguments to `pickNextInterval` with `Union`s.

**Comment by r-k-b** [comment]
@Kr00lIX Try now - it should come up as [2.0.1](https://package.elm-lang.org/packages/r-k-b/elm-interval/2.0.1/)

**Comment by Kr00lIX** [comment]
Thank you very much! It works! 🎆

**Pull request merged**
